### ISSUE TITLE
Add-on manager interface needs improvements

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2023]
All problems are observed when resolution is set to 1024x768 in 1.13.8+dev master

- [ ]  When you click "Remove addon" or "Install addon" icons in addon description, "Back to List" button title remains, even though clicking this button makes drops interface to main list, where it is named "Addon Details". Clicking it two times restores proper title. Either, installing addon from addon description dialog should not drop user out of addon-details, or dropping should be complete. Related to #1993.

- [ ] Status of dummy addon with _server.pbl is displayed as "Published" after manipulations described in first checkbox.

- [] Attempt to remove the addon which was incorrectly displayed as "Published" caused crash:
Caught general 'N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_9iostreams10gzip_errorEEEEE' exception: gzip error: iostream error

- [ ] Same exception crash is sometimes produced during attempts to install add-ons, for example when I tried to install addon again after cancelling its download with esc key.

- [ ] Hitting Esc button in Addon Details or Addon List dialog now does nothing.  From details it should drop user back to addon list. When it's clicked in addon list it should probably close addon manager, but it's ok if it does nothing, since if you use it and click two times accidently you don't want to lose current addon list filters and position in the list. Related to #1995.

- [ ] Perhaps, double click on addon should display its information rather than installing or removing it right away or accidental removal or installation of addons becomes too easy. 

- [ ] Perhaps an entry in addon list should display a tooltip with addon description like it happens in online version

- [ ] Relative width of columns in not configurable. Default width doesn't seem to be optimal.

- [ ] "Last updated" column is not displayed at all, while rather useless "version" column is. Related to #1747

**Comment by sapientN3T** [comment]
This is labeled as an Enhancement, but it actually contains some bugs. For example, the "Back to List" incorrect label is a bug.

**Comment by Vultraz** [comment]
Second entry about the status state was fixed here: c1841e3fe84fcffd896b282b3596a696b5a717b7

**Comment by vgaming** [comment]
> Status of dummy addon with _server.pbl is incorrectly displayed as "Published" after manipulations described in first checkbox

Confirming that the bug is still present. Only you don't have to do any kind of manipulations at all. Just a dummy _server.pbl and you get the add-on label "Published" (even when it's not).

**Comment by Wedge009** [comment]
I was wondering why I couldn't find any 'add-on details' page - it's only available when the window size is small enough that only the add-on list can be displayed. I normally have a wide enough view that details are shown to the right of the add-on list. That aside, agree that Esc should allow one to return from details to the list page, and then from the list back to the main menu.

I also didn't realise until afterwards that double-click was interpreted as an install command (while I was looking for aforementioned details page).

**Comment by Wedge009** [comment]
The double-click question is duplicated in #4901.
