### ISSUE TITLE
MP lobby regressions list

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2538]
All of these work correctly for 1.12.
- [x] #1194 important to have, I need it most to see pregame chat
- [ ] #1206 would be great to have, but not vital
- [x] #1200 I have nothing against those boxes, but they could start opened by default
- [ ] #1199 ~~most likely fixed, but needs testing before closing~~ broken on 1.13
- [x] #3191
- [x] #3185

https://forums.wesnoth.org/viewtopic.php?f=6&t=47302 discussion results not included here.

**Comment by Vultraz** [comment]
The last one is technically "fixed" since in order to see a player in-game in the new lobby you need to select that game.

**Comment by Vultraz** [comment]
Dunno, probably not.

**Comment by ProditorMagnus** [comment]
I confirmed that you can select people from "other games" list, and selecting them does not change currently selected game - that means #1199 is still relevant and regression.

**Comment by CelticMinstrel** [comment]
Missing from this list: rooms don't even exist server-side. I think there's an issue for this but not quite sure.

**Comment by ProditorMagnus** [comment]
I mentioned that room commands dont work in #2500, but not separately.

**Comment by wesnothmint** [comment]
#1199 is not very minor. In busy periods when there are 30+ games open it is much faster to find the game that a particular player is in by clicking on their name. Isar's cross is one that is particularly common and will often have 4+ games adjacent to each other on the list of games.

Combining this with the game title (where the host's name is listed) now being smaller than the scenario name (a sub-optimal design choice), if a player disconnects and wants to reenter, it will take longer to find their game.

**Comment by ProditorMagnus** [comment]
Just checked in mp server, and #1200 and #1199 are more annoying than I initially said.

**Comment by vgaming** [comment]
Possibly related: https://github.com/wesnoth/wesnoth/issues/2538  "game list not informative"

**Comment by Wedge009** [comment]
Does #3196 qualify for this list?

**Comment by ProditorMagnus** [comment]
No, that command worked in game too, not just in lobby.

**Comment by ProditorMagnus** [comment]
Dont see the value to keep this issue open anymore. Not useful to track regressions compared to years old version.
