### ISSUE TITLE
Forward port

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3514]
- [x] 106692beb0 769dd6239c - merge cleanly
- [x] 38a85190b8 - conflict (help_impl.cpp was renamed)
- [x] 6772682b7c8d5cabf1b676f0deb5324019855ad3 - #3473 
- [x] d4a7aa281513ff5373bdb538d308e5dc20af24c4, b7b86c1bf74b77fd59d3344772be49ccb30573fe, 0cb4484714c4c09872c71c21033536d03375c09d - #3459
- [x] https://github.com/wesnoth/wesnoth/commit/b7cb36a7116d687e4bbaeae32336c0d1dd7e2e0b - #3544 #3546 - PR #3555
- [x] changelog entry for #3330
- [x] changelog entry for #3533
- [x] 1e5452d3b6cb0d0b0bcc762c3f5d580f69e5141d 3f3ee230932c415f5adb8af23ae3bc23ddc62ca8 - #3568
- [x] https://github.com/wesnoth/wesnoth/commit/461cd2c4bdeb2eb0e84ede6e57cd0b315dee2cee
- [x] the battery PR #3441 
- [x] a521db8136f5a2eb8398287c934a3d2d3f268121 #3577
- [x] 8000a868286d374d39c71215de6f376a31e4fe0a #3572 (part of #3633)
- [x] 5e97d1505f529c45ff8e48f694b6fd938b56e3af #3187 (done in 91db37daabbdc9de42e2d158408ccdf898c992ef)
- [x] c08491f704636f85c4e59fab97b27204dd074ad9 ea6c955e7bb0e5e52f41453b129469aa16e3ea3d #3256 
- [x] the commits of #3602 (battle_combat refactor)
- [x] 0119413 and 1597a2c (ai use custom recall cost)
- [x] 247e08e (only if ar is reverted)

I only checked my PRs. There are a few hundred 1.14 commits that don't have matching commits in master, I don't know how many of those need to be fwdported.

edit: Add 3473 etc

**Comment by Pentarctagon** [comment]
I've forward ported 106692b and 769dd62.  IIRC the entire ingame Help is in a state of flux in master at the moment, so I don't know if 38a8519 would be applicable anymore.

**Comment by Pentarctagon** [comment]
@Vultraz Should 38a8519 be forward ported to master, or would it be for 1.14 only?

**Comment by CelticMinstrel** [comment]
It's about generated topics, so it may well be still applicable on master.

**Comment by gfgtdf** [comment]
the commits of https://github.com/wesnoth/wesnoth/pull/3602 (battle_combat refactor)

01194139 and 1597a2ce (ai use custom recall cost)

247e08e1d521 (only if ar is reverted)

**Comment by mattsc** [comment]
Just saw this.  Both AI custom recall cost commits have been in master since April 2018: e1da42ea91 c4ebb1cea6

**Comment by mattsc** [comment]
As is @gfgtdf 's last in the list up there, if I see that right: 94a9dbe9272a4

So I think this can be closed.
