### ISSUE TITLE
Issues that may need to be reopened

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3622]
I diffed the logs of old master and new master for issue references and found these - they are mentioned on old master's log but not on new master's.

- [x] Fixed crash when starting the editor (fixes #2816)
- [x] Fixed halos drawing over fog and shroud (fixes #1406)
- [x] Fixes #1568
- [x] Fixes #1744
- [x] Fixes #2724.
- [x] Fixup 66dc671 (fixes #2887)
- [x] Fixup ea5945b (fixes #3221)
- [ ] Merge pull request #2840 from newfrenchy83/patch-11
- [x] Merge pull request #3506 from mattsc/lua_ai_cleanup
- [x] Merge pull request #3555 from jostephd/objectives-prestart-for-master
- [x] Note on the last point: When I fixed bug #1772 (aa8f6c7e7 right now but will probably change with rebasing)
- [x] See #2863.
- [x] See #2927.
- [ ] Update wesnoth.cbp (#2890)

As well as three [issues tagged "Fixed on AR branch" and closed] not in the above list:

- [x] #1617
- [x] #1563 
- [x] #1400
- [x] #1350 Visual problems with halos on edge

Everyone, please go through these and **tick the boxes of the ones you handled**, either by reopening them or by determined that they are closed are are indeed fixed on current (new) master. When all boxes are ticked this issue can be closed.

**Comment by Wedge009** [comment]
I ticked #2816 as working for (new) master.

**Comment by Wedge009** [comment]
Re-opened #1406, ticked here.
 
Sorry I didn't clarify #2724 - the forum account creation is on the official server only. It's a requirement in 1.14, so I suppose it should be there for 1.15/master (especially since the log-in screen for multi-player specifies that a Wesnoth account is necessary). Created #3624 for this.

#2863 is a minor issue, I don't think it would need to be in the milestone but I'm ticking it here because it's an open and valid issue.

Ticking #1563 because it doesn't appear to be an issue currently.

Added #1350 and ticked it because it's re-opened.

**Comment by mattsc** [comment]
Checked #3506 as all commits in it are already cherry-picked to new master.

**Comment by GregoryLundberg** [comment]
Checked 1617 closed by bcbac9fe33d990a65578bdbeccc29474568e0cdd

**Comment by jostephd** [comment]
Ticked #3555. The fix is present on new master, it's in this list because #3603 didn't recreate merge commits.

**Comment by jostephd** [comment]
Ticked #1400. The cages in _The Bay of Pearls_ show behind the flags. https://github.com/wesnoth/wesnoth/commit/126d435748ac4afbdff351cee89221d5633bb6b8

**Comment by Vultraz** [comment]
Reopened those. Unfortunately they cannot be fixed without the direct-to-screen texture rendering I had implemented.

**Comment by jostephd** [comment]
@Vultraz Thanks, I've ticked them off here.

**Comment by jostephd** [comment]
Everything except cbp is handled so this is no longer a blocker.

**Comment by jostephd** [comment]
Any objections to just closing this? There's nothing more to do here unless someone wants to audit the cbp files.
