### ISSUE TITLE
1.16 Checklist

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#4750]
Put anything you want to do for 1.16 here, including any issue or PR references if applicable.

**Comment by CelticMinstrel** [comment]
With varying levels of urgency…

* [ ] #4580
* [ ] #993
* [ ] #3414
* [ ] #1033
* [ ] New Lua GUI2 API (insert forum thread here)
* [ ] Maaaybe the thing allowing Lua to define WFL functions (lua_formula_bridge branch)
* [ ] Completion of rearranged Lua API

My top priorities are the map stuff (both). If I think of anything else I'll add it later.

**Comment by gfgtdf** [comment]
I'd still like to add https://github.com/wesnoth/wesnoth/pull/3576 that is, adding an 'api level' api that allows us to add new functions during stable releases.

**Comment by Pentarctagon** [comment]
#2710

**Comment by nemaara** [comment]
Campaigns:

* [ ]  Finish working on Liberty S7
* [ ]  Finish updating SoF S1
* [ ]  Finish redrawing the remaining UtBS maps
* [ ]  Possibly complete #4747 (not certain)
* [ ]  Start working on additional SoF improvements (dialogue and prettifying maps, not plot/lore updates)
* [ ]  Potentially work on updating TRoW gameplay (#4533)

Units:

* [ ]  Second pass revision for reworked elvish descriptions
* [ ]  Possibly finish remaining (unreworked) elvish descriptions
* [ ]  Begin adding new lore into orcish/undead descriptions 
* [ ]  Merge #4577 pending more balancing changes (also needs @soliton-'s approval)
* [ ]  Merge #4748 pending additional discussion

**Comment by sigurdfdragon** [comment]
- [ ] Drake Campaign: Wings of Victory (or whatever it might be called)

**Comment by stevecotton** [comment]
What does this checklist do instead of using the milestone lists?
* https://github.com/wesnoth/wesnoth/milestone/20
* https://github.com/wesnoth/wesnoth/milestone/13

- [ ] #4280 Agree on what the difficulty levels are meant to mean
- [ ] #2964 Documentation for the Scenario Editor (or removing half-implemented stuff if it's broken)
- [ ] #4454 Balancing for the new mushrooms

**Comment by CelticMinstrel** [comment]
I don't know Vultraz's reasoning, but my list here was more wishlist than must-have.

**Comment by Pentarctagon** [comment]
Just putting everything under a generic "by 1.16" milestone isn't much help either though, and you can't really come up with anything more specific without knowing what people actually want to do first.

**Comment by GregoryLundberg** [comment]
And it's hard to discuss the milestones without an Issue for that purpose.

**Comment by Pentarctagon** [comment]
Also, for what I myself am looking to do:
- [ ] Finish up the travis renovations I've been working on (almost done).
- [ ] Get some sort of answer on [this](https://travis-ci.community/t/concurrency-for-open-source-projects/3827/4) question/problem.
- [ ] Implement at least the "Store the versions of add-ons used." item of #4284.
- [ ] Implement some sort of UI to allow players to query the recorded game history, either in-game from the MP lobby or maybe from the website.

**Comment by sevu** [comment]
Thing's I have on my list
- [ ] Changing core macros for unit placement to use random_gender=yes (optional or by default)
- [ ] Considering whether core macros should give an overlay to loyal units or not
- [ ] Rebalancing prices of some factionless units, as if they would be part of a faction.
      In particular Chocobone, Mud Crawler, Cuttlefish, Wose Sapling and alike
- [ ] Dropping some [units](https://r.wesnoth.org/t51648)
- [ ] Resolving #4670
- [ ] Merging #4340 (ready, but hold back)
- [ ] Having wmllint run on all campaigns #4494
- [ ] Porting ANL to Lua #4382, also #1149
- [ ] Change naga descriptions #4591
- [ ] merge German 1.14 po files into master
- [ ] Getting German translation up to date
- [ ] Change animation code of Fire Guardian: Flame should come from the center like with the Fire Dragon
- [ ] deprecate [advancefrom] in favour of [modify_unit_type], maybe removing ifdefs which were added in 1.15 #4762
- [ ] consider changing ^Vm terrain code to include Vt basetype
- [ ] why does ctrl +t not work for some terrains, especially for unorthodox combinations?

**Comment by CelticMinstrel** [comment]
More detail in the forum post, but I am categorically _against_ removing any of those units @sevu

**Comment by Pentarctagon** [comment]
As a reminder here as well, the 1.15 roadmap is [here](https://wiki.wesnoth.org/1.15_Roadmap) with dates for each point release.  Please move any changes that are still relevant and have yet to be made to a point release there.

Additionally, a thread for any discussion or questions about the roadmap is [here](https://forums.wesnoth.org/viewtopic.php?f=2&t=52786).
