### ISSUE TITLE
Undocumented Lua functions, WML tags and attributes

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5175]
Support for these has been added to the engine, but there's no hint about them on the Wiki. Making it a checklist, so it's easy to add stuff.

WML:
- [ ] `[campaign]scenario_define`, found in src/game_classification.cpp and mentioned in #1404
- [ ] `[scenario]define=` (or is it `[multiplayer]define=` ?), mentioned in #1404
- [ ] `[advancement][filter]`, added in #4495 

Lua:
- [ ] `wesnoth.interface.get_items()`, added in #5091

**Comment by CelticMinstrel** [comment]
Should we add the new GUI2 API to this list? The `gui.widgets` module and other related stuff.

**Comment by gfgtdf** [comment]
> [campaign]scenario_define, found in src/game_classification.cpp and mentioned in #

I'm pretty sure that no such tag exists.

> [scenario]define= (or is it [multiplayer]define= ?), mentioned in #1404

The main usecase here is [multiplayer] define= (afaik its even used in mainline for ANL)

**Comment by CelticMinstrel** [comment]
`scenario_define` clearly exists, since it's present in the code. However, I did a quick code search for it and get the impression that it's an internal implementation detail related to `[scenario]define=`?

> The main usecase here is [multiplayer] define= (afaik its even used in mainline for ANL)

The main use-case is in multiplayer, but I'm guessing it will work in any scenario, right?

**Comment by gfgtdf** [comment]
> scenario_define clearly exists, since it's present in the code. However, I did a quick code search for it and get the impression that it's an internal implementation detail related to [scenario]define=?

That's more likely.

> The main use-case is in multiplayer, but I'm guessing it will work in any scenario, right?

I don't know

**Comment by stevecotton** [comment]
Thanks for the corrections - I confirm that the `scenario_define` attribute isn't part of `[campaign]` - it's part of SavefileWML and appears outside any tag (as part of the serialization of `game_classification`), and is otherwise an internal implementation related to `[scenario]define=`.

**Comment by sevu** [comment]
- [ ] [remove_trait]

**Comment by CelticMinstrel** [comment]
Just noting that the GUI2 API has been covered.

**Comment by sevu** [comment]
- [ ] The Lua tag got a new attribute, to give the block a name, which will be shown in stack traces. I don't remember the name of … maybe it was even simply called name.

**Comment by CelticMinstrel** [comment]
* [] The `ref=` key in ThemeWML is undocumented.

**Comment by stevecotton** [comment]
- [ ] `wesnoth.colors`, example usage in https://github.com/wesnoth/wesnoth/pull/5723#discussion_r619599914

**Comment by stevecotton** [comment]
- [ ] WFL `side_number` and similar added in #5805

**Comment by stevecotton** [comment]
- [ ] Lua's `wesnoth.scenario`, noted in https://r.wesnoth.org/p670667

**Comment by CelticMinstrel** [comment]
[https://wiki.wesnoth.org/LuaAPI/wesnoth#wesnoth.scenario](That's documented.)

**Comment by stevecotton** [comment]
Ah, I see how vghetto and I got confused. Have added a hint above the [submodules list](https://wiki.wesnoth.org/LuaAPI#Wesnoth_Modules) to search in Core too.

**Comment by CelticMinstrel** [comment]
Seeing @Elvish-Hunter add documentation for `gui.get_user_choice` reminded me that there are a few other functions I also still haven't documented.

* [ ] `wesnoth.interface.move_unit_fake`
* [ ] `wesnoth.units.modify`
* [ ] `wesnoth.units.teleport`
* [ ] `wesnoth.units.create_weapon`
* [ ] `wesnoth.sides.all_teams`
* [ ] `wesnoth.get_era` - although I'm a little unsure if this is considered API or if it should be "do not use"; it _was_ documented in LuaWML, I think
* [ ] `wesnoth.get_resource` - probably "do not use", as it was added in analogy to `get_era` but never actually documented
* [ ] `wesnoth.get_language`
* [ ] `wesnoth.map.get_in_basis_N_NE` - I skipped it because I'm not sure if it's good enough to be considered API
* [ ] `wesnoth.map.vector_diff`, `wesnoth.map.vector_negation`, `wesnoth.map.vector_sum`
* [ ] `ilua._pretty_print` - but maybe this is an internal detail?
* [ ] The `ai-helper` module - @mattsc had a reason for that, I think, so I left it alone

**Comment by mattsc** [comment]
I think the reason for the `ai_helper` module was simply that it was still in flux with potentially significant changes possible at any time, as stated in the comment at the beginning of the file.  But that's not the case any more, so I think that comment should be removed and the functions can be added to the documentation.

**Comment by Elvish-Hunter** [comment]
Another undocumented key is `overwrite_specials=`, which can be used in `[abilities] [chance_to_hit]`, but isn't mentioned in the AbilitiesWML wiki page.

**Comment by CelticMinstrel** [comment]
I ticked off `[scenario]define=` which is now documented in [AddonsWML](https://wiki.wesnoth.org/AddonsWML), as well as `[lua]name=` which is documented in [LuaWML](https://wiki.wesnoth.org/LuaWML#The_.5Blua.5D_tag). I also ticked off `wesnoth.interface.get_items()` and four of the Lua things listed in my previous post.

**Comment by ProditorMagnus** [comment]
https://github.com/wesnoth/wesnoth/commit/8144c063896092390638bae0b57abb5368de2510 added wesnoth.interface.screen_fade

**Comment by ProditorMagnus** [comment]
wesnoth.map.filter_tags

**Comment by CelticMinstrel** [comment]
> wesnoth.map.filter_tags

Semi-documented [here](https://wiki.wesnoth.org/LuaAPI/wesnoth/map#wesnoth.map.find) but could definitely use a bit more explanation.
