### ISSUE TITLE
[SoF] S4 Gathering Materials: Make mining gold and coal clearer

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6154]
### First Proposal
In the scenario Gathering Materials from Sceptre of Fire.
I propose adding a narrator-hint after this line:
https://github.com/wesnoth/wesnoth/blob/dd3baa488150bfc8d8cd0105da9083009cb29ca0/data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg#L705
Something which says "Dwarvish Miners are the  only units that can fetch and carry gold and coal."

#### Rationale
Yes, the existing dialog states this somewhat, but it can't hurt to improve clarity by restating the intention from a meta-perspective, further eliminating any remote chance of misinterpretation.

Alternatively, this could be an objective note instead of narrator-hint. Or both if desired.

### Second Proposal
Add an event that triggers when a hex containing gold and coal is revealed. For the event, scroll the map to center the gold/coal hex onscreen and make the hex border/flash blink using a colored border highlight. Have the unit that reveals the hex say something like "I found coal!" and "I found gold!"

#### Rationale
The player might not be aware when and where gold and coal have already been discovered - putting the mouse on the hex containing the gold and coal only says the terrain and does not confirm it is the gold/coal. The only way to confirm is to actually send a unit to it, which can be annoying if the player's units are already very far. Additionally, coal can be difficult to spot on the map due to its low contrast with the cave terrain.

#### Screenshot
Coal has been revealed on the map but I was completely unaware.
![image](https://user-images.githubusercontent.com/41433185/135995631-a68d4059-8205-4812-a232-36929da6ae6a.png)

### Third Proposal
Make Scenario Objectives concise. Scenario objectives is not the place for any kind of story context such as "to create the sceptre", and the second objective is more of a note than an objective.
Current objectives:
![image](https://user-images.githubusercontent.com/41433185/136001676-e7271b25-2f56-42a9-9066-6f4aa7f6db12.png)

### Task List
- [x] Add narrator-hint (or objectives note) about using miners
- [ ] Add event that highlights gold and coal upon discovering it on the map
- [x] Make Scenario Objective concise

Replay attached (version 1.15.18):
[SoF-Gathering Materials replay 20211004-164355.gz](https://github.com/wesnoth/wesnoth/files/7284487/SoF-Gathering.Materials.replay.20211004-164355.gz)

**Comment by max-torch** [comment]
This existing code:
https://github.com/wesnoth/wesnoth/blob/dd3baa488150bfc8d8cd0105da9083009cb29ca0/data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg#L765-L790
and this existing  code:
https://github.com/wesnoth/wesnoth/blob/dd3baa488150bfc8d8cd0105da9083009cb29ca0/data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg#L868-L886
Can already serve as a starting point for accomplishing the second task.
