### ISSUE TITLE
UtBS S6b In_the_Domain_of_Dwarves Bugs and Issues

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6196]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

#### Describe the bug
If the dust devil or Elyssa triggers the Dwarf Sergeant dialog, the dwarves call the dust devil or Elyssa a troll.

#### To Reproduce

1. Trigger the dwarf sergeant dialog with the dust devil or Elyssa, and keep other units away to make sure only the dust devil was recognized.
2. Dwarves believe they see a troll.

#### Expected behavior
Dwarves should see a dust devil and say "what in the Earth's Guts is that?"
Upon seeing Elyssa, the Dwarves could say "What's a little girl like you doing here? Are you lost?"

#### Screenshots
![image](https://user-images.githubusercontent.com/41433185/137583348-86f8c4db-1ac6-4b2c-a763-b4f48f984794.png)

#### Savefile
Dust Devil Replay: 
[dust devil.gz](https://github.com/wesnoth/wesnoth/files/7357345/dust.devil.gz)

#### Describe the bug
A unit can get stuck in an impassable cave wall (either 16,31 or 23,30) during the scripted event where the Dwarvish Stalwart seals the tunnel.

#### To Reproduce

1. Send a unit close enough to the Dwarvish Stalwart (17,31 or 22,30) but far enough not to trigger the event.
2. End Turn.
3. Move the unit next to the Dwarvish Stalwart.
4. After the dialog, the unit is stuck inside a cave wall.

#### Expected behavior
No units should suddenly be getting stuck in walls. If the player manages to get beside the dwarf in one turn, I suggest changing the dialog to say "Woah, where did you come from! Get out of there, you're standing on the fuse! You sneaky little elf/troll/floating mound of dust/mage!" and then the wall cave-in never occurs, the player is rewarded for quickly sneaking up on the guard.

#### Screenshots
Unit is one turn away:
![image](https://user-images.githubusercontent.com/41433185/137583750-40783b78-fd00-48ee-91f1-e6075f7e6c4c.png)
Unit is now stuck:
![image](https://user-images.githubusercontent.com/41433185/137583764-d9296de5-7734-4c19-9322-12fd2b7279c4.png)

#### Savefile
[unit can get stuck.gz](https://github.com/wesnoth/wesnoth/files/7357385/unit.can.get.stuck.gz)

#### Describe the bug
It's possible to spot the spawn in of Grog with a quick unit.

#### To Reproduce

1. With a unit that can see far. send the unit close enough that it can spot the hex Grog is supposed to appear on but far away enough not to trigger the event. You will see that the hex is empty.
2. End Turn
3. Move in to trigger the event. You will see Grog spawn.

#### Expected Behavior
The player doesn't see a dwarf staring at an empty hex then suddenly see that hex populated with Grog.

#### Screenshot
Player can see the empty hex Grog will spawn on:
![image](https://user-images.githubusercontent.com/41433185/137584200-78f58c9b-50de-41de-95f9-0a5baf21104d.png)

#### Savefile
[Grog spawn.gz](https://github.com/wesnoth/wesnoth/files/7357395/Grog.spawn.gz)

#### Describe the bug
Sometimes, the tentacles don't show up in the lake when the dialog "What are those?" shows onscreen.

#### To Reproduce
Not sure, what the exact cause of the bug is, but below I have examples of different people encountering the same thing - this bug is far too common.

#### Expected Behavior
Tentacles should be on the map while the dialog is onscreen.

#### Screenshot
The tentacles don't appear:
![image](https://user-images.githubusercontent.com/41433185/137584354-3d797566-553b-4939-9de9-5539a16cd12a.png)
Expected behavior:
![image](https://user-images.githubusercontent.com/41433185/137584364-830a170f-01f2-4408-8c9c-c04e90879e2c.png)

#### Youtube video
Courtesy of Konrad2
https://youtu.be/8PdcEZGlago?t=2551

#### Savefiles
Konrad2's replay: https://forums.wesnoth.org/viewtopic.php?p=667789#p667789
My own reproduction of the issue: 
[again no tentacle.gz](https://github.com/wesnoth/wesnoth/files/7357417/again.no.tentacle.gz)
Maiklas 3000's replay from 1.11.15 also has the bug: https://forums.wesnoth.org/viewtopic.php?p=571079#p571079

#### Describe the bug
A Dwarvish Pathfinder that is supposed to be part of the bridge fight in the middle can wander into the Dwarf chieftain area and get sealed in when the bomb that seals the tunnel detonates. The player later encounters this pathfinder in the lake as he walks all the way around.

#### To Reproduce
Not sure how to always make this happen. Probably when the player puts formidable units on the bridge that the dwarf side does not want to attack and instead some dwarf units will choose to run away. It has managed to happen to me more than once.

#### Expected Behavior
All units in the Bridge fight stay to fight

#### Screenshots:
Pathfinder is running away:
![image](https://user-images.githubusercontent.com/41433185/137584620-b1753c15-f3dc-40a0-b3e1-71026039c562.png)
Pathfinder is closed off by the detonation:
![image](https://user-images.githubusercontent.com/41433185/137584660-07193a06-574d-4fd3-a053-64a4b88fea81.png)

#### Savefile
[pathfinder replay.gz](https://github.com/wesnoth/wesnoth/files/7357426/pathfinder.replay.gz)

#### Describe the bug
It is possible for the player to miss the hermit dialog which goes
https://github.com/wesnoth/wesnoth/blob/ce08eda7f8b5f37b2b39dfe2e2dcc7cebd52299d/data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg#L1522
if the hermit is baited out into the water and killed.

#### To Reproduce
Send a unit close enough to the hermit's island. The hermit will move into the water and attack. Kill the hermit.

#### Expected Behavior
The player always gets to see the hermit dialog. Make it trigger when the hermit sights the player, rather than depending on having units step on the island.

#### Screenshot
The hermit has been baited out:
![image](https://user-images.githubusercontent.com/41433185/137585044-71bec77d-cb46-4c8e-916c-0ea5479699ee.png)

#### Savefile
[some missed hermit dialog.gz](https://github.com/wesnoth/wesnoth/files/7357440/some.missed.hermit.dialog.gz)

### Task List
- [x] Dust Devil and Elyssa mistaken as troll
- [x] Unit gets stuck in cave wall
- [x] Player sees empty hex of Grog
- [x] First wave of tentacles do not spawn but dialog plays
- [x] Pathfinder runs away and gets stuck on the other side
- [x] Player can miss some hermit dialog

The highest priority in this list would be the tentacle issue.

**Comment by Descacharrado** [comment]
> If the dust devil or Elyssa triggers the Dwarf Sergeant dialog, the dwarves call the dust devil or Elyssa a troll.

That is not a bug, it is intended to work like that. The joke is that the dwarf is with his back turned away from the entrance and he is not seeing what was entering the room. Race differenciation is already implemented in the dialogue. Code from lines 657 - 701:
``` [if]
            [variable]
                name=unit.race
                equals=quenoth
            [/variable]
            [or]
                [variable]
                    name=unit.race
                    equals=elf
                [/variable]
            [/or]
            [then]
                [message]
                    x,y=9,36
                    message= _ "No, it’s an elf!"
                [/message]
                [modify_unit]
                    [filter]
                        id=Dwarf Sergeant
                    [/filter]
                    facing=se
                [/modify_unit]
                [message]
                    id=Dwarf Sergeant
                    message= _ "What...?! Right... First task, boys, kill the intruder!"
                [/message]
            [/then]
            [else]
                [message]
                    x,y=9,36
                    message= _ "I’m too young to die, save me!"
                [/message]
                [modify_unit]
                    [filter]
                        id=Dwarf Sergeant
                    [/filter]
                    facing=se
                [/modify_unit]
                [message]
                    speaker=Dwarf Sergeant
                    message= _ "Oh, grow a backbone... Huh? Hey, for once the runt was telling the truth. Come on, boys, kill the intruder!"
                [/message]
            [/else]
        [/if]
    [/event]

**Comment by Descacharrado** [comment]
> Sometimes, the tentacles don't show up in the lake when the dialog "What are those?" shows onscreen.

I used debug mode to see where the tentacles were spawning, sometimes it tells me legit coords (where they would then spawn) such as 28 16:

![Sin título 2](https://user-images.githubusercontent.com/30196839/137586579-945a65c3-a7c1-4106-9c5a-8230ab692d8d.png)

But sometimes, when no tentacle can be seen, this happens:

![Sin título](https://user-images.githubusercontent.com/30196839/137586556-a03e5b60-4adf-4921-951a-75c73a3798bb.png)

I know nothing about what Im about to say but _**it looks like overflow????**_

**Comment by max-torch** [comment]
> > If the dust devil or Elyssa triggers the Dwarf Sergeant dialog, the dwarves call the dust devil or Elyssa a troll.
> 
> That is not a bug, it is intended to work like that. The joke is that the dwarf is with his back turned away from the entrance and he is not seeing what was entering the room. Race differenciation is already implemented in the dialogue. Code from lines 657 - 

Yes it's a bug. If its not an elf the dwarf sergeant says "for once the runt was telling the truth". The "truth" in the context of the dialog was that a troll was behind him.

**Comment by Descacharrado** [comment]
> The implemented race differentiation is only between elf and troll. You have to take into account the preceding line before this is "What? There's a troll behind me?"

I stand corrected, differentiation should be between elf, troll, the dust devil race and Elyssa's race then, I see.

**Comment by max-torch** [comment]
> I can attempt this since I will be redesign the _Final Confrontation_, so might as well do both UtBS issues. Hmm, about the tentacles...do they appear in deep water...so that _submerge_ is activated?

They dont even appear. The first wave is completely absent.

**Comment by Wedge009** [comment]
It's a bit hard to engage with a report like this - even though it's all from the same scenario, it might have been better to make separate reports, especially so PRs can close individual tasks as they're resolved.

1. Given the dwarves are always fighting the trolls, it doesn't seem unreasonable that any unit they see that isn't one of their own, they would assume is the enemy. Though it is true that the original author does account for elf vs troll, so I suppose it's an enhancement to make the dwarves account for the dust devil and Elyssa too. #6198 appears to cover this.
2. This is a tricky situation that isn't limited to this scenario, eg I've seen it in the trap room at the north-west corner of Northern Rebirth's 'The Pursuit' scenario (the 'spider ambush' event). I agree it would be nice to avoid this situation though, eg maybe push back the unit after closing the wall - but there's also the potential for multiple units to be clogging that passage too...

The remainder I feel are general issues as well. Also with respect to the last one about the hermit being drawn out - it's possible to miss plenty of events in any scenario. I suppose it's dependent on how likely the author wants the player (without foreknowledge) to see these.

**Comment by Descacharrado** [comment]
> Pathfinder runs away and gets stuck on the other side

I discovered why he does that, it is because he is a dwarvish scout and he has the goal of taking the village north and he may prefer that to waiting to attack on the chokehold. I do not know how to fix the problem tho, I may look into it.

**Comment by Descacharrado** [comment]
@Wedge009 This can now be closed.

**Comment by Wedge009** [comment]
Thanks for your efforts.
