### ISSUE TITLE
UtBS S6b In_the_Domain_of_Dwarves - Improve Amulet Easter Egg Logic

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6197]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### Suggestion 1
Make sure Grog doesn't die in the fight where he is introduced. It happens probably 1 out of every 5 games. Perhaps use scripted forced hits and misses.

#### Screenshots
Before even getting close. Grog has already taken so many hits and is about to die. His health bars is practically empty.
![image](https://user-images.githubusercontent.com/41433185/137586369-915ba0e3-93aa-4abd-bce7-fa636b89d1ab.png)

#### Savefile
[Grog death replay.gz](https://github.com/wesnoth/wesnoth/files/7357489/Grog.death.replay.gz)

#### Rationale
Practically all players will restart once they see Grog die like this.

#### Forum complaints of this
The complaint is inside the spoiler tag:
- https://forums.wesnoth.org/viewtopic.php?p=581506#p581506

### Suggestion 2
Improve amulet easter egg logic. Currently, when the player kills the dwarf hermit the player finds an amulet. Somehow, this amulet is teleported all the way across the lake to the unit that steps on the rune. I have two suggestions to improve this:
- Place a rune on the hermit island. Make a unit wearing the amulet step on that rune at the same time the unit across the lake also steps on their rune become the requirement that opens the way to the crypt.
- Make the unit that steps on the rune ask "can we examine that amulet for clues?" and then the person who found the amulet says "there is writing on the amulet which says 'speak friend'". And then the unit across the lake also says 'speak friend' and is surprised to see the way to the crypt open.

#### Forum complaints of this
- https://forums.wesnoth.org/viewtopic.php?p=624948#p624948
- https://forums.wesnoth.org/viewtopic.php?p=498263#p498263

### Suggestion 3
When the dwarf sentinel on the bridge dies, and triggers the sealing of the south tunnel that leads to the dwarf chieftain, it's possible for the player to not see what exactly occurred. We get that some detonation took place but it's not clear where. I suggest scrolling the map to the spot where the tunnel gets closed, lifting the fog, then making the explosion happen which closes the tunnel, so that the player can clearly see it.

#### Screenshot
We learn that a charge has been detonated, but we have no idea where and for what purpose. It lacks context when it is introduced.
![image](https://user-images.githubusercontent.com/41433185/137586869-0075a97d-408f-495d-b0fd-c245d8f7eb6a.png)

### Suggestion 4
Remove some additional fungus that was added in commit 8d9894aab7103f30a6070e9431df0d703f499cc0. Specifically, the ones that are below the hermit island, on the way leading up to the dwarf chieftain entrance. They make the scenario more difficult because they impede the movement of the trolls. Trolls need to spend 2MP to walk through fungus whereas the previous cave terrain only cost 1MP for them to move through. Now, if the player wants to use the same old tactic of getting units into the dwarf cave before the dwarves can block it, the player has to look up the trigger zone that starts activating the recruitment of the dwarf lord.

#### Screenshots
Before adding fungus. See how many turns required to get into position:
![image](https://user-images.githubusercontent.com/41433185/137587146-eb36ab89-f126-45db-ac35-51ed4441bb3a.png)
After adding fungus:
![image](https://user-images.githubusercontent.com/41433185/137587170-7eb4a4a6-da94-4863-a328-cff40a989990.png)
What the player has to do to compensate is compress units in the spot just before the trigger zone:
![image](https://user-images.githubusercontent.com/41433185/137587321-72926300-54d3-44a9-a0b5-564fe7e17e1e.png)

### Suggestion 5
Add 'thunderer miss' sound effect when Dwarven Sentinel's charge fails to detonate

#### Screenshot
The sound effect should play right after this dialog to signify that the charge failed:
![image](https://user-images.githubusercontent.com/41433185/137587439-06cf06c4-5c33-44d6-a8a8-32f4d65ec2ff.png)

### Task List
- [x] Make sure Grog doesn't die
- [ ] Improve amulet easter egg logic
- [x] scroll to detonation that occurs when the bridge commander dies
- [x] Remove fungus that increases scenario difficulty
- [x] Add 'charge failed' sound effect for when the second dwarf sentinel fails to blow up his charge.

**Comment by Wedge009** [comment]
Looks like the only thing outstanding is the handling of the amulet? Re-reading this I started from the beginning and thought to myself 'I thought Grog's death was already addressed'... indeed it was.

**Comment by max-torch** [comment]
AFAIK it's only the amulet remaining
